Homework 16
Otus-DevOps-2017-11/frodox_microservices pull request #3
Opened 2018-03-11 21:55 UTC by Frodox

* Проба создания Dockerfile для микросервисного приложения
* Пробы по оптимизации размера/создания Docker образов
* Запуск микросервисного приложения вручную
* Использование volume для перманентного сохранения данных

2018-03-12 18:56 UTC, serjs commented on reddit-microservices/post-py/Dockerfile
> +COPY . .
А почему копируем файлы после entrypoint?

2018-03-12 18:57 UTC, serjs commented on reddit-microservices/post-py/Dockerfile
> +ENV POST_DATABASE_HOST post_db
ENV переменные приложения лучше выносить перед запуском самого приложения, так и нагляднее и в случае смены или дополнению таких, не придется пересобирать немалую часть образа после них

2018-03-12 18:58 UTC, serjs commented on reddit-microservices/post-py/Dockerfile
> +ENV POST_DATABASE_HOST post_db
Ну и обрати внимание что APP переменная используется у нас только для сборки, но в таком варианта она имеет место на суещствтование вверху, есть более явная инструкция для таких случаев

2018-03-12 18:59 UTC, serjs requested changes
Привет!

Я отписал в комментах на места, которые рекомендую изменить. Блокирующим считаю COPY после entrypoint

2018-03-13 21:03 UTC, Frodox commented on reddit-microservices/post-py/Dockerfile
> +COPY . .
Потому что слой с entrypoint никогда не меняется, это просто инструкция, аля USER, а файлы мы копируем/добавляем постоянно, при изменении оных в каталоге

2018-03-14 14:47 UTC, serjs approved these changes

2018-03-14 17:24 UTC, Frodox commented on reddit-microservices/post-py/Dockerfile
> +ENV POST_DATABASE_HOST post_db
Это да. Но нужно смотреть что чаще меняется. Обычно код меняется намного чаще чем переменные эти вот) и во встречаемых мною докерфайлах вверху обычно видел. Но учту

2018-03-14 17:30 UTC, merged

2018-03-18 11:58 UTC, Frodox commented
@serjs в ЛК otus ДЗ по прежнему помечено как не сданное :(